VIA_ENABLE = no
AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
EXTRAKEY_ENABLE = yes
# -flto saves ~14% on firmware size
#EXTRAFLAGS += -flto
CONSOLE_ENABLE = no