VIA_ENABLE = yes
AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
EXTRAKEY_ENABLE = yes
# -flto saves ~14% on firmware size
EXTRAFLAGS += -flto
CONSOLE_ENABLE = no
COMBO_ENABLE = no
NKRO_ENABLE = no
