VIA_ENABLE = no
AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = no
# enter qmk console to see the output
CONSOLE_ENABLE = yes
COMBO_ENABLE = no
NKRO_ENABLE = yes
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
SWAP_HANDS_ENABLE = no
#SRC += muse.c