VIA_ENABLE = no
AUTO_SHIFT_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
EXTRAKEY_ENABLE = yes
# -flto saves ~14% on firmware size
EXTRAFLAGS += -flto
CONSOLE_ENABLE = yes
RGBLIGHT_ENABLE = yes
